#version: "3"

#docker run -d -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=zippy -e MONGO_INITDB_ROOT_PASSWORD=skippy --name mongo --network mongo-network mongo
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/db:/data/db
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - mongo-network
      
#docker run -d -p 8081:8081 -e ME_CONFIG_MONGODB_SERVER=mongo -e ME_CONFIG_MONGODB_ADMINUSERNAME=admin -e ME_CONFIG_MONGODB_ADMINPASSWORD=password --name mongo-express --network mongo-network mongo-express
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    # restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      #- ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      #- ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
